### ISSUE TITLE
ELK做前端统计

### ISSUE THREAD

**Issue by sophister** [ErosZy/ELK.md#1]
hi，基于 `ELK`  实现web前端的监控系统，有在生产环境实践么？我也有类似的想法，但是没看到业界有这样做的呢

**Comment by ErosZy** [comment]
一大堆，微博，百度，头条等等

**Comment by sophister** [comment]
额，上面几个我没看到有公开资料，百度这些应该是自己实现的存储吧，我只看到 [这篇美团](https://juejin.im/post/5a3e121451882533f01ec66d) 的文章有提到。你那有其他几家的介绍文章么？

PS：github上回复都这么及时，和微信有一拼了啊

**Comment by ErosZy** [comment]
> 额，上面几个我没看到有公开资料，百度这些应该是自己实现的存储吧，我只看到 [这篇美团](https://juejin.im/post/5a3e121451882533f01ec66d) 的文章有提到。你那有其他几家的介绍文章么？
> 
> PS：github上回复都这么及时，和微信有一拼了啊

如果要自己建设前端监控体系，直接用成熟的云服务就好，比如阿里云的loghub。如果是做elk的整套体系建设，专业的人做专业的事儿吧。
